### ISSUE TITLE
After setting up getting requireNode errors

### ISSUE THREAD

**Issue by sinukus** [dotbc/dotbc-bundler#4]
After setting things up with Node.js 7.0 everything launches, but when I open localhost:4200 I get:

plugin.js:8 Uncaught TypeError: requireNode is not a function
    at Module.callback (plugin.js:8)
    at Module.exports (loader.js:114)
    at Module._reify (loader.js:148)
    at Module.reify (loader.js:135)
    at Module.exports (loader.js:112)
    at Module._reify (loader.js:148)
    at Module.reify (loader.js:135)
    at Module.exports (loader.js:112)
    at requireModule (loader.js:29)
    at index.js:18

This is from latest chrome. The error occurs when I build from OSX or PC.

I see that the index file does try to set this up, but I still see the error.

Also there are a few missing dependencies, bower, ember-inflector. Would be nice to see these added.

**Comment by mateodelnorte** [comment]
HI @sinukus. Looks like you're building and attempting to load in chrome, probably via `npm start`. This is a little bit legacy, and you can load the electron app directly on your machine. There are also some utility scripts for loading those missing dependency tools that you mentioned. 

I updated the README.md to have instructions for installing those tools, installing default plugins, and running for development purposes locally in this commit: 6997d872ee1822d96f0ccde45044d0614a6731af

Check out the updated [Readme](https://github.com/dotbc/dotbc-bundler/blob/master/README.md#running-and-developing-locally) for the full details. 

Let me know if this gets you past your issue.

**Comment by sinukus** [comment]
Thanks for adding to the read.me.

I ran the install tools script on OSX and it completes, when I then run
npm run electron
I end up with a blank page in the electron app. Looking at the devtools console I see:

DEPRECATION: In Ember 2.0 service factories must have an `isServiceFactory` property set to true. You registered (unknown mixin) as a service factory. Either add the `isServiceFactory` property to this factory or extend from Ember.Service. [deprecation id: ember-application.validate-type]
        at HANDLERS.(anonymous function) (file:///code/dotbc-bundler/dist/assets/vendor.js:16502:7)
        at raiseOnDeprecation (file:///code/dotbc-bundler/dist/assets/vendor.js:16410:12)
        at HANDLERS.(anonymous function) (file:///code/dotbc-bundler/dist/assets/vendor.js:16502:7)
        at invoke (file:///code/dotbc-bundler/dist/assets/vendor.js:16518:7)
        at deprecate (file:///code/dotbc-bundler/dist/assets/vendor.js:16471:32)
        at Object.deprecate (file:///code/dotbc-bundler/dist/assets/vendor.js:26510:37)
        at Object.validateType [as default] (file:///code/dotbc-bundler/dist/assets/vendor.js:16331:24)
        at exports.default._emberRuntimeSystemObject.default.extend.resolve (file:///code/dotbc-bundler/dist/assets/vendor.js:16026:51)
        at resolve (file:///code/dotbc-bundler/dist/assets/vendor.js:12594:36)
ember.debug.js:28535Error while processing route: works.index "%@:%@".fmt is not a function TypeError: "%@:%@".fmt is not a function
    at _key (file:///code/dotbc-bundler/dist/assets/dotbc-desktop.js:3147:22)
    at unknownProperty (file:///code/dotbc-bundler/dist/assets/dotbc-desktop.js:3118:32)
    at Object.get (file:///code/dotbc-bundler/dist/assets/vendor.js:30967:20)
    at exports.default._emberMetalMixin.Mixin.create.get (file:///code/dotbc-bundler/dist/assets/vendor.js:45537:38)
    at .initAuthData (file:///code/dotbc-bundler/dist/assets/dotbc-desktop.js:3060:40)
    at Object.sendEvent (file:///code/dotbc-bundler/dist/assets/vendor.js:26993:25)
    at new Class (file:///code/dotbc-bundler/dist/assets/vendor.js:47006:25)
    at Function.ClassMixinProps.create (file:///code/dotbc-bundler/dist/assets/vendor.js:47260:14)
    at instantiate (file:///code/dotbc-bundler/dist/assets/vendor.js:11649:23)
    at lookup (file:///code/dotbc-bundler/dist/assets/vendor.js:11487:17)logError @ ember.debug.js:28535
ember.debug.js:32096TypeError: "%@:%@".fmt is not a function
    at _key (local-storage.js:44)
    at unknownProperty (local-storage.js:15)
    at Object.get (ember.debug.js:20818)
    at exports.default._emberMetalMixin.Mixin.create.get (ember.debug.js:35388)
    at .initAuthData (auth.js:15)
    at Object.sendEvent (ember.debug.js:16844)
    at new Class (ember.debug.js:36857)
    at Function.ClassMixinProps.create (ember.debug.js:37111)
    at instantiate (ember.debug.js:1500)
    at lookup (ember.debug.js:1338)onerrorDefault @ ember.debug.js:32096
Failed to parse SourceMap: http://localhost:30820/socket.io/socket.io.js.map

Windows instructions seems to be still off with watchman requiring brew in mingw64.

**Comment by mateodelnorte** [comment]
I'm able to start from scratch and get completely up and running with just the following: 

`git clone git@github.com:dotbc/dotbc-bundler.git && cd dotbc-bundler && yarn && make install-tools && npm run electron`. 

When electron pops up, it looks like this:
<img width="807" alt="screen shot 2017-05-18 at 12 17 21 pm" src="https://cloud.githubusercontent.com/assets/554847/26212613/1e4a28fe-3bc4-11e7-8e6d-131e584dff87.png">

Running `make install-plugins` in the mix also works: 

`git clone git@github.com:dotbc/dotbc-bundler.git && cd dotbc-bundler && yarn && make install-tools && make install-plugins && npm run electron`. 

I'm running node v7.1.0 on Mac. 

The Deprecation warning you see in the dev console is normal, and just a warning. It's not a sign of error. 

Can you give that a try, fresh? And, if you're still having problems, share more info about your OS, exact node version, npm version, etc?

**Comment by sinukus** [comment]
ah, yeah, I now get to the log in page. I hadn't installed yarn, might want to add that to the read.me.

Is there a similar command for windows?

**Comment by mateodelnorte** [comment]
Same command. You can also use `npm install` in place of yarn. It's a drop
in replacement.

On May 18, 2017 12:49 PM, "sinukus" <notifications@github.com> wrote:

ah, yeah, I now get to the log in page. I hadn't installed yarn, might want
to add that to the read.me.

Is there a similar command for windows?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/dotbc/dotbc-bundler/issues/4#issuecomment-302468510>,
or mute the thread

**Comment by sinukus** [comment]
On windows running under gitbash I hit the brew dependency:

/usr/bin/sh: line 4: brew: command not found
make: *** [Makefile:27: install-tools] Error 127

Not sure how to add brew to gitbash on windows.

**Comment by mateodelnorte** [comment]
brew only exists on macs. These are just helper commands to automate getting all the tools you need. There may be extra steps for getting up and running on Windows. 

Sounds like the remaining two steps you have are installing these two: 
- https://facebook.github.io/watchman/docs/install.html 
- http://phantomjs.org

Manual installs should be fine.

**Comment by sinukus** [comment]
yeah, thats what I thought about brew.

Installing watchman and phantom.js in the the mingw64 bin folder worked, so I can now launch on windows and mac.

Now just need to get a login.

Thanks for the help to get up and running!

**Comment by mateodelnorte** [comment]
Glad to help!
